Per breakpoint (per row) plots
d3b-center/annoFuse pull request #41
Opened 2020-08-27 19:11 UTC by kgaonkar6

## Description
The breakpoints are being plotted per Sample and FusionName selected as of yesterday's PR samplespecific_bpplots .
After discussing with @jharenza  we also want to plot specific breakpoint per Sample per FusionName.  

Which cane done in the core plot_breakpoints() as as follows :
left <- plot_breakpoints(sampleid = "BS_044XZ8ST", 
                         domainDataFrame = domainDataFrame, 
                         exons = exons, 
                         geneposition = "Left", 
                         fusionname = "ANTXR1--BRAF",leftBreakpoint = "69152264")

In addition , I also a added the max_count limit to take the aggreagted fusionName count in plot_recurrent_genes and plot_recurrent_fusions.

## Request to reviewers
Please review the conditions to plot which are: 
If sample is not NULL plot for the specific sample
If leftBreakpoint/rightBreakpoint is not NULL then plot for specific breakpoint

## Changes affecting shiny_fuse
I guess for shiny_fuse the checkbox should be plot per breakpoint in the row? @federicomarini to add more information here.

2020-08-28 01:12 UTC, jharenza commented
This seems to still show per sample plots for me, even when unchecking the box as default. Can you make the default be per row? Eg: `BS_044XZ8ST`

<img width="1354" alt="Screen Shot 2020-08-27 at 9 12 30 PM" src="https://user-images.githubusercontent.com/207034/91510086-0d184480-e8aa-11ea-8492-450589b71449.png">

2020-08-28 01:14 UTC, jharenza requested changes
see comment

2020-08-28 06:50 UTC, federicomarini commented
> @federicomarini can you make the default plot per row and then users can check if they want to see by sample?
Sure!

2020-08-28 08:50 UTC, federicomarini commented
> This seems to still show per sample plots for me, even when unchecking the box as default. Eg: BS_044XZ8ST

Can that be because there is only one sample anyway?
I did follow the path of the code via `message` commands and it seems to be correct.

2020-08-28 14:25 UTC, kgaonkar6 commented
Hi @federicomarini , to make it per row I think you'll have to provide the specific breakpoint to the function , accessing that per row as follows 

      fusion_for_content <- values$annofuse_tbl[row_id, "FusionName"]
      samplespec <- values$annofuse_tbl[row_id, "Sample"]
      right_breakpoint <- values$annofuse_tbl[row_id, "RightBreakpoint"]

So then the following code will changed from this
https://github.com/d3b-center/annoFuse/blob/5fba25e109979bad54d5c3e4986106bb0a7c5c0f/R/shiny_fuse.R#L505-L519

to something like
```
if(input$bp_plot_samplespecific) {
        p <- plot_breakpoints(
          domainDataFrame = values$ann_domain,
          exons = values$data_exons,
          geneposition = "Right",
          sampleid = samplespec,
          fusionname = fusion_for_content,
          rightBreakpoint = right_breakpoint
        ) 
      } else {
        p <- plot_breakpoints(
          domainDataFrame = values$ann_domain,
          exons = values$data_exons,
          geneposition = "Right",
          fusionname = fusion_for_content
        )
      }

```

2020-08-28 14:31 UTC, kgaonkar6 commented on R/shiny_fuse.R
> +               width = 20,
maybe longer width for both the plots?
```suggestion
               width = 30,
```

2020-08-28 21:48 UTC, kgaonkar6 reviewed
buttons work like a charm!

I think all the points for breakpoint plots are being addressed in this PR.   @federicomarini and @jharenza  to approve changes

2020-08-29 00:11 UTC, jharenza commented
looks good

2020-08-29 00:11 UTC, merged